openapi: 3.0.1
info:
  title: Submit Proposal Data
  version: 1.0.0
  description: >-
  
    # Overview
  
    Proposal application submission can be done using this API. The response of 'Get API' (data section) becomes the request body for Submit Proposal API. Under each field, the attribute "input" has to be added which whill carry the value entered/selected by the customer for each field.
  
  x-logo:
    url: "https://1silverbullet.tech/assets/images/Logo.svg"
    backgroundColor: "#FFFFFF"
    altText: "1SB Logo"
servers: 
- url: /insurance
paths:
  /:
    get:
      summary: "Submit Proposal API"
      responses:
        200:
          description: Submit Proposal application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubmitProposalRequest'
      x-consumer-request-api: all
      x-consumer-request-api-auth:
        type: basic Authorization
        httpMethod: POST
        requestParameters:
          integration.request.header.custom_h1: method.request.header.h1
        responses:
          2\d{2}:
            statusCode: "200"
          404:
            statusCode: "404"
            description: "Not Found"
          default:
            statusCode: "400"
            responseParameters:
              method.response.header.test-method-response-header: '''static value'''
            responseTemplates:
              application/json: json 400 response template
              application/xml: xml 400 response template
      x-codegen-request-body-name: RequestBodyModel     
components:
  schemas: 
    SubmitProposalRequest:
      type: object
      properties:
        reqId:
          description: "Request Id for the get proposal request assigned by 1SB"
          type: string
        errors:
          description: "This array contains error messages in case of an error"
          type: array
          items:
            type: object
        data:
          description: "Section to carry responses"
          type: object
          properties:
            manufacturerId:
              description: "This will help to identify the insurance company to which the product belongs."
              type: string
              example: "ICICI"
            productId:
              description: "The product for which the below information has been provided."
              type: string
              example: "My Term Product"
            productGroupId:
              description: "The product group (term, savings, ULIPS etc) is identified through this field."
              example: "LifeTerm"
              type: string
            fieldGroups:
              description: "This section will carry multiple sub field groups and fields. Each field will carry attributes which give additional information. example: name, description, type, pattern, order, visibility, validation, mandatory, etc"
              type: object
    SubmitProposalResponse:
      type: object
      properties:
        status:
          type: object
          properties:
            code:
              description: "Status code"
              type: string
            message:
              description: "Status message"
              type: string
        error:
          type: array
          items:
            type: object
            properties:
              code:
                description: "Error code"
                type: string
              message:
                description: "Error message"
                type: string
        ISBTracking:
          type: object
          properties:
            1SBproposalReferenceId:
              description: "Transaction Id generated by 1SB for each proposal submission"
              type: string
            1SBQuoteRequestID:
              description: "Quote ID generated by 1SB for Single quote"
              type: string
            varFields:
              type: array
              description: "Additional fields for 1SB tracking section"
              items:
                type: object
                properties:
                  fieldName:
                    description: "Name of additional field"
                    type: string
                  fieldValue:
                    description: "Value of additional field"
                    type: string
        ManufacturerTracking:
          type: object
          properties:
            quoteID:
              description: "quotation ID"
              type: string
            applicationNumber:
              description: "proposal application number"
              type: string
            policyNumber:
              description: "policy number"
              type: string
            varFields:
              type: array
              description: "Additional fields for manufacturerTracking section"
              items:
                type: object
                properties:
                  fieldName:
                    description: "Name of additional field"
                    type: string
                  fieldValue:
                    description: "Value of additional field"
                    type: string
        URL:
          type: object
          properties:
            policyURL:
              description: "policy URL"
              type: string
            paymentURL:
              description: "URL for Payment redirection to manufacturers website"
              type: string
            resumeJourneyURL:
              description: "URL given by manufacturer to resume to proposal process on their website"
              type: string
            varFields:
              type: array
              description: "Additional fields for URL section"
              items:
                type: object
                properties:
                  fieldName:
                    description: "Name of additional field"
                    type: string
                  fieldValue:
                    description: "Value of additional field"
                    type: string
        medicals:
          type: object
          properties:
            isMedicalReq:
              description: "Is medical check up required for submitted proposal? (Yes/ No)"
              type: string
            typeOfMedical:
              description: "What type of medical check is applicable. example: Physical medical, tele medical, etc."
              type: string
            varFields:
              type: array
              description: "Additional fields for URL section"
              items:
                type: object
                properties:
                  fieldName:
                    description: "Name of additional field"
                    type: string
                  fieldValue:
                    description: "Value of additional field"
                    type: string
        varFields:
          type: array
          description: "Additional fields for proposal response"
          items:
            type: object
            properties:
              fieldName:
                description: "Name of additional field"
                type: string
              fieldValue:
                description: "Value of additional field"
                type: string
    Error:
      type: object
x-consumer-request-api:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true
x-consumer-request-api-: params-only